# Generated by Django 4.0.4 on 2022-04-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('artist', models.CharField(max_length=30)),
                ('release_year', models.IntegerField()),
                ('featured', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
